"""Verified local reading sheets. This reader never imports a cloud SDK."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

from pydantic import BaseModel, ConfigDict, Field, model_validator


class BriefSection(BaseModel):
    model_config = ConfigDict(frozen=True)
    label: str = Field(min_length=1, max_length=90)
    summary: str = Field(min_length=1, max_length=650)
    quote: str = Field(min_length=8, max_length=1000)
    pinpoint: str = Field(min_length=1, max_length=90)


class BriefDraft(BaseModel):
    model_config = ConfigDict(frozen=True)
    sections: list[BriefSection] = Field(min_length=1, max_length=5)

    @model_validator(mode="after")
    def bounded(self):
        if sum(len(s.summary.split()) for s in self.sections) > 280:
            raise ValueError(
                "Keep summaries within 280 words for a one-page reading sheet."
            )
        return self


def verify_draft(doc, draft: BriefDraft):
    """A citation must point to an actual contiguous passage, never a stitched quote."""
    sections = []
    for section in draft.sections:
        start = doc.text.find(section.quote)
        if start < 0:
            raise ValueError(
                "A supporting quote is absent from the source; draft refused."
            )
        sections.append(
            {**section.model_dump(), "start": start, "end": start + len(section.quote)}
        )
    return sections


def load_brief(doc, directory: Path):
    """Invalidate both the PDF and its claims when source text or generated bytes change."""
    try:
        folder = directory.resolve()
        manifest = (folder / f"{doc.id}.json").resolve()
        if not manifest.is_relative_to(folder):
            return None
        data = json.loads(manifest.read_text())
        if data["text_sha256"] != doc.text_sha256 or data["document_id"] != doc.id:
            return None
        sections = verify_draft(
            doc, BriefDraft.model_validate({"sections": data["sections"]})
        )
        pdf = (folder / f"{doc.id}.pdf").resolve()
        if not pdf.is_relative_to(folder) or pdf.stat().st_size > 2_000_000:
            return None
        raw = pdf.read_bytes()
        if hashlib.sha256(raw).hexdigest() != data["pdf_sha256"]:
            return None
        return {"method": data["method"], "sections": sections}, raw
    except (OSError, ValueError, KeyError, TypeError):
        return None


def editorial_card(doc):
    """Show reviewed card metadata only for exactly the text that was checked."""
    try:
        config = Path(__file__).parent / "config" / "court_briefs.json"
        data = json.loads(config.read_text()).get(doc.id)
        if data is None or data["text_sha256"] != doc.text_sha256:
            return {}
        return {
            "issue": data["issue"],
            "outcome": data["outcome"],
            "charge_summary": data["sections"][0]["summary"],
        }
    except (OSError, ValueError, KeyError, TypeError):
        return {}
